name: med

# The packages we depend on. You may (but need not) comment out
# anything you don't actually use.
dependencies:
- base             # For built-in functions like `length`
- containers       # For Data.Map
- parsec           # Uncomment this if you use Parsec for the parser
- tasty            # The test framework Tasty
- tasty-hunit      # unit-testing with Tasty
- QuickCheck       # for property-based testing
- tasty-quickcheck # QC-testing with Tasty

# The basic library
library:
  source-dirs: src
  exposed-modules:
    - SpecAst
    - SpecParser


# A simple command-line driver, that uses the library
executable:
  main: Main.hs
  source-dirs: src